### ISSUE TITLE
Androidx ViewModel

### ISSUE THREAD

**Issue by Shakezulla57** [googlecodelabs/android-dagger#1]
I think this code lab could benefit from showing how to use Dagger with an Androidx ViewModel and ViewModelFactory.

**Comment by manuelvicnt** [comment]
I understand the necessity for this content today. However, the team is currently focused on bringing the best AndroidX support experience to the new Dagger initiative for Android that will come soon. 

Stay tuned for that as there will be direct support and no work arounds will be needed.
