### ISSUE TITLE
Problem at tab Multiple Activities With Same Scope

### ISSUE THREAD

**Issue by TheMaxCoder** [googlecodelabs/android-dagger#12]
First of all, I would like to thank you for the great codelab, beautiful explanation. Even as an experienced user of dagger I learned a lot from it 👏👌

There is this extra line, which I think should not be there at the bottom of the tab  `Multiple Activities With Same Scope` 

as we are in the `MainActivity`, `setContentView()` is setting a view of `activity_settings`

I am attaching a screenshot for reference.

![image](https://user-images.githubusercontent.com/16763485/69630372-b6f24880-106e-11ea-8aad-69c42588c621.png)

Thank you!

**Comment by manuelvicnt** [comment]
Thank you! This should be fixed now :)

**Comment by JakeSteam** [comment]
Nope, still there!
